import type { Cut, OverlayLayer } from '../types';
import { formatTime } from '../utils/time';
import OverlayCanvas from './OverlayCanvas';
import OverlayInspector from './OverlayInspector';
import PlaybackControls from './PlaybackControls';
import WaveformTimeline from './WaveformTimeline';

type Props = { duration: number; peaks: number[]; cuts: Cut[]; selectedCutId: string | null; currentTime: number; isPlaying: boolean; zoom: number; flashing: boolean; loopEnabled: boolean; loopWindow: number; overlays: OverlayLayer[]; selectedOverlayId: string | null; selectedOverlay: OverlayLayer | null; onZoom: (z: number) => void; onSeek: (t: number) => void; onTogglePlay: () => void; onAddCut: (t: number) => void; onMoveCut: (id: string, t: number) => void; onSelectCut: (id: string | null) => void; onRemoveCut: (id: string | null) => void; onLoopEnabled: (v: boolean) => void; onLoopWindow: (v: number) => void; onSelectOverlay: (id: string | null) => void; onUpdateOverlay: (id: string, update: Partial<OverlayLayer> | ((overlay: OverlayLayer) => OverlayLayer)) => void; onAddOverlay: (type: 'text' | 'logo' | 'cta') => void; onDeleteSelectedOverlay: () => void; onResetIntroOverlay: () => void };
export default function EditorLayout(p: Props) { const selected = p.cuts.find((cut) => cut.id === p.selectedCutId); return <main className="flex min-h-0 flex-1 flex-col gap-3 bg-premiere-950 p-4"><div className="grid grid-cols-2 gap-3 text-sm lg:grid-cols-4"><div className="rounded bg-premiere-900 p-3">Duration: <span className="font-mono text-white">{formatTime(p.duration)}</span></div><div className="rounded bg-premiere-900 p-3">Cuts: <span className="font-mono text-white">{p.cuts.length}</span></div><div className="rounded bg-premiere-900 p-3">Overlays: <span className="font-mono text-white">{p.overlays.length}</span></div><div className="rounded bg-premiere-900 p-3">Selected cut: <span className="font-mono text-white">{selected ? formatTime(selected.time) : '—'}</span></div></div><div className="flex min-h-0 flex-1 flex-col gap-3 lg:flex-row"><OverlayCanvas overlays={p.overlays} selectedOverlayId={p.selectedOverlayId} currentTime={p.currentTime} flashing={p.flashing} onSelectOverlay={p.onSelectOverlay} onUpdateOverlay={p.onUpdateOverlay}/><OverlayInspector selectedOverlay={p.selectedOverlay} onAddOverlay={p.onAddOverlay} onDeleteSelected={p.onDeleteSelectedOverlay} onResetIntro={p.onResetIntroOverlay} onUpdateOverlay={p.onUpdateOverlay}/></div><WaveformTimeline peaks={p.peaks} duration={p.duration} cuts={p.cuts} selectedCutId={p.selectedCutId} currentTime={p.currentTime} zoom={p.zoom} overlays={p.overlays} selectedOverlayId={p.selectedOverlayId} onZoom={p.onZoom} onSeek={p.onSeek} onAddCut={p.onAddCut} onMoveCut={p.onMoveCut} onSelectCut={p.onSelectCut} onRemoveCut={p.onRemoveCut} onSelectOverlay={p.onSelectOverlay} onUpdateOverlay={p.onUpdateOverlay} isPlaying={p.isPlaying}/><PlaybackControls currentTime={p.currentTime} isPlaying={p.isPlaying} loopEnabled={p.loopEnabled} loopWindow={p.loopWindow} onToggle={p.onTogglePlay} onLoopEnabled={p.onLoopEnabled} onLoopWindow={p.onLoopWindow}/></main>; }
